name: Artifact Pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    name: CI Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Creating file
        run: echo "Hello world" >> data.txt
      - name: Upload artifatcs
        uses: actions/upload-artifact@v4
        with:
          name: charan
          path: data.txt
  deploy:
    needs: [ build ]
    name: CI Container
    runs-on: ubuntu-latest
    steps:
      - name: Creating file
        run: echo "Hello world" >> data.txt
      - name: Upload artifatcs
        uses: actions/download-artifact@v4
        with:
          name: charan
      - name: show file
        run: ls