name: Java version call Pipeline
on:
  workflow_dispatch:
    inputs:
      java_ver:
        default: '17'
        type: choice
        options:
          - '11'
          - '12'
jobs:
  build:
    name: CI Deployment
    uses: tcslabscharan/gh-actions/.github/workflow/hello.yaml@v1
    with:
      java_ver: ${{ inputs.java_ver }}