name: Selfhosted Pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Self hosted runner
    runs-on: self-hosted
    steps:
      - name: Creating file
        run: echo "Hello world" >> data.txt
      - name: Upload artifatcs
        uses: actions/upload-artifact@v4
        with:
          name: charan
          path: data.txt